### ISSUE TITLE
Zip Codes may have more than one state

### ISSUE THREAD

**Issue by llimllib** [wrobstory/zipwhich#1]
[Le wik](http://en.wikipedia.org/wiki/ZIP_code) says:

> Because ZIP codes are intended for efficient postal delivery, there are unusual cases where a ZIP code crosses state boundaries, such as a military facility spanning multiple states or remote areas of one state most easily serviced from an adjacent state. For example ZIP code 42223 spans Christian KY and Montgomery TN, and ZIP code 97635 spans Lake OR and Modoc CA.

**Comment by wrobstory** [comment]
If you look at the `renamed_final` dataset, it addresses the "one zip, multiple states" thing. I suppose I could add it as a third dataset (vs. the unique zip). 

Part of the reason of getting distinct zips is that for my purposes, I need a concrete answer for a given zip, and I'll probably be matching city/state name as well.
